backend:
  name: git-gateway
  branch: master

media_folder: src/images
public_folder: ../src/images

collections:
  - name: "news"
    label: "News"
    folder: "news"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Page Type", name: "pagetype", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

