backend:
  name: git-gateway
  branch: master

media_folder: "src/images/uploads"
public_folder: "/src/images/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "news"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Page Type", name: "pagetype", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "taiken"
    label: "体験醸造"
    folder: "taiken"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "info-itabashi"
    label: "Info Itabashi"
    folder: "info/itabashi"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Type", name: "pagetype", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "info-yurakucho"
    label: "Info Yurakucho"
    folder: "info/yurakucho"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Type", name: "pagetype", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "food-taproom"
    label: "Food Taproom"
    folder: "food"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown" }


